apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: todo-app
          image: karim2324/todo-app:latest  # <-- Replace this
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection
                  key: MONGO_URI
